apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-forbid
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: ubuntu
              image: remote-docker.artifactory.swisscom.com/weibeld/ubuntu-networking
              command: [sleep, infinity]
