apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deployment-2
  template:
    metadata:
      labels:
        app: my-deployment-2
    spec:
      containers:
      - image: remote-docker.artifactory.swisscom.com/weibeld/ubuntu-networking
        name: ubuntu-networking
        command: [sleep, infinity]
