apiVersion: batch/v1
kind: Job
metadata:
  name: onfailure
spec:
  backoffLimit: 2
  template:
    spec:
      initContainers:
        - image: remote-docker.artifactory.swisscom.com/weibeld/ubuntu-networking
          name: ubuntu-init
          command: [sh, -c, 'sleep 5; date, -x']
      containers:
        - image: remote-docker.artifactory.swisscom.com/weibeld/ubuntu-networking
          name: ubuntu-fail
          command: [sh, -c, 'sleep 10; date, -x']
#        - image: remote-docker.artifactory.swisscom.com/weibeld/ubuntu-networking
#          name: ubuntu-ok
#          #command: [sh, -c, 'sleep 120; date, -x']
#          command: [sleep, infinity]
      #imagePullSecrets:
      #- name: sdweb-docker-local
      restartPolicy: OnFailure
