apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
spec:
  serviceName: rfs-testredis
  replicas: 1
  selector:
    matchLabels:
      app: my-sts
  template:
    metadata:
      labels:
        app: my-sts
    spec:
      hostNetwork: true
      containers:
      - image: remote-docker.artifactory.swisscom.com/weibeld/ubuntu-networking
        name: ubuntu-networking
        command: [sleep, infinity]
        ports:
          - containerPort: 8080
            hostPort: 8080
